### ISSUE TITLE
Что-то недовыложили

### ISSUE THREAD

**Issue by VZhyrytskiy** [maksim-paulau/ang-webinars#11]
ng serve -o
Команда не запускает проект. Нехватает файлов в ветке Task5

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-12-06T13:19:59.144Z
Hash: 4bb79e2479bfe1692dd3
Time: 7868ms
chunk {main} main.js, main.js.map (main) 1.86 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.01 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 318 kB [initial] [rendered]

ERROR in src/app/app.component.ts(2,29): error TS2307: Cannot find module './cart/services/cart.service'.
src/app/app.module.ts(10,34): error TS2307: Cannot find module './app-routing.module'.
src/app/app.module.ts(12,39): error TS2307: Cannot find module './layout/components/path-not-found/path-not-found.component'.
src/app/app.module.ts(13,32): error TS2307: Cannot find module './layout/components/login/login.component'.
src/app/cart/cart.module.ts(7,57): error TS2307: Cannot find module './cart-routing.module'.
src/app/cart/cart.module.ts(8,36): error TS2307: Cannot find module './components/order-form/order-form.component'.
src/app/cart/cart.module.ts(9,31): error TS2307: Cannot find module './cart.component'.
src/app/cart/components/cart-list/cart-list.component.ts(2,29): error TS2307: Cannot find module '../../services/cart.service'.
src/app/cart/components/cart-list/cart-list.component.ts(6,30): error TS2307: Cannot find module '../../services/order.service'.
src/app/products/components/product-list/product-list.component.ts(4,29): error TS2307: Cannot find module '../../../cart/services/cart.service'.
src/app/products/products.module.ts(6,39): error TS2307: Cannot find module './products-routing.module'.
src/app/products/products.module.ts(7,41): error TS2307: Cannot find module './components/product-details/product-details.component'.
src/app/products/products.module.ts(8,38): error TS2307: Cannot find module './components/product-edit/product-edit.component'.
src/app/products/products.module.ts(10,42): error TS2307: Cannot find module './components/product-feedback/product-feedback.component'.

i ｢wdm｣: Failed to compile.

**Comment by maksim-paulau** [comment]
Пофикшено
