### ISSUE TITLE
cart.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [maksim-paulau/ang-webinars#7]
addProduct(product: IProduct): void {
    this.products.push(product);
    product.isAvailable = false;   <--- Опасное изменение свойства
    this.summary += product.price;
  }

product - передается по ссылке, поскольку это объект. Изменение свойства внутри метода приводит к изменению этого свойства снаружи. Если вы так и задумывали, ок.

**Comment by maksim-paulau** [comment]
Да, так задумывалось, хотя и выглядит небезопасно, согласен. В следующих коммитах будет реализован счетчик по каждому товару, и этот метод будет переписан.

**Comment by VZhyrytskiy** [comment]
ок
